# Generated by Django 4.0.10 on 2025-03-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decimal_places',
            new_name='price',
        ),
    ]
